### ISSUE TITLE
JSONAPI::Serializable::UndefinedSerializableClass: No serializable class defined for User::Perspective

### ISSUE THREAD

**Issue by rgaufman** [jsonapi-rb/jsonapi-serializable#122]
I renamed the Perspective model to User::Perspective. It is the same serializable model:

```
tether-x(dev)> User::Perspective.where(user_id: 'a')
=> #<Mongoid::Criteria
  selector: {"user_id"=>"a"}
  options:  {}
  class:    User::Perspective
  embedded: false>
```

However I get this exception now for: 

```
def index
  render jsonapi: User::Perspective.where(user_id: user_id)
end
```

This is the exception:

```
  1) Api::V3p::PerspectivesController GET#index Authorised returns list of perspectives with jsonapi style
     Failure/Error: render jsonapi: User::Perspective.where(user_id: user_id)

     JSONAPI::Serializable::UndefinedSerializableClass:
       No serializable class defined for User::Perspective
     # /opt/homebrew/lib/ruby/gems/3.1.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable.rb:28:in `resource_for'
     # /opt/homebrew/lib/ruby/gems/3.1.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable.rb:16:in `block in resources_for'
     # /opt/homebrew/lib/ruby/gems/3.1.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable.rb:15:in `map'
     # /opt/homebrew/lib/ruby/gems/3.1.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable.rb:15:in `resources_for'
     # /opt/homebrew/lib/ruby/gems/3.1.0/gems/jsonapi-serializable-0.3.1/lib/jsonapi/serializable/renderer.rb:45:in `render'
     # /opt/homebrew/lib/ruby/gems/3.1.0/gems/jsonapi-rails-0.4.0/lib/jsonapi/rails/renderer.rb:16:in `render'
```

Any ideas?

**Comment by rgaufman** [comment]
Ah, the solution here helped! < https://github.com/jsonapi-rb/jsonapi-rails/issues/68
